export const fontFamilies = [
  "Gill Sans Extrabold",
  "sans-serif",
  "Goudy Bookletter 1911",
  "serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded",
  "emoji",
  "math",
  "fangsong",
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
];
